### ISSUE TITLE
Stuck on container build

### ISSUE THREAD

**Issue by neutt22** [richdynamix/arc#1]
Running `docker-compose up` left me here:
![image](https://user-images.githubusercontent.com/8733987/38292023-c561e60c-3814-11e8-9160-3cf98d5ad2e4.png)

I'm installing on a 5.5 project.

**Comment by neutt22** [comment]
Nevermind. I just removed this package to my project.

**Comment by richdynamix** [comment]
@neutt22 I have no idea why I never got notified of this issue. How long was it stuck for? First time builds can take a little longer as it needs to build everything and there is no cache. I use this daily on everything from Laravel 5.2 to Laravel 5.6
