### ISSUE TITLE
Can't set ENV values

### ISSUE THREAD

**Issue by plexcellmedia** [richdynamix/arc#14]
I'm trying to set environment values, but when I run:
`docker-compose up`

I get error:
```
WARNING: The GITHUB_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The DOCKER_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DOCKER_REPO variable is not set. Defaulting to a blank string.
WARNING: The TAG variable is not set. Defaulting to a blank string.
ERROR: no such image: :: invalid reference format
```

If I set changes directly to .env file, it runs, but then .env file gets replaced because of this:
```
web_1       | 2019-03-22T00:59:11Z 8b5c712b95c8 confd[62]: INFO /app/.env has md5sum 42eef3fa36719640e318f6611ebf5474 should be 3dfe187a2ac10b52c088e70a29b83b34
web_1       | 2019-03-22T00:59:11Z 8b5c712b95c8 confd[62]: INFO Target config /app/.env out of sync
web_1       | 2019-03-22T00:59:11Z 8b5c712b95c8 confd[62]: INFO Target config /app/.env has been updated
```

This is every file where I have set my env configuration and I have even changed default configs, but it gets replaced by default values, even thought I cant find references to default values in any file. Maybe I am doing something wrong, but what?

![envs](https://user-images.githubusercontent.com/12846005/54795383-b0484180-4c54-11e9-9653-05f4a2eeec10.png)

**Comment by richdynamix** [comment]
Adding these to your docker-compose file will resolve this issue - See the stubs that are created for you - https://github.com/richdynamix/arc/blob/master/stubs/docker-compose-cicd.yml
