### ISSUE TITLE
confusing readme, not prompted for CI/CD configuration unless using dev-master

### ISSUE THREAD

**Issue by vesper8** [richdynamix/arc#16]
I followed the Readme's steps

```
Require the package in your project
    composer require richdynamix/arc
Run the installer
    php artisan arc:install
You will be prompted to choose if you want CI/CD configurations.

    Would you like a Travis CI and K8s CD configuration? (yes/no) [no]:
Once complete the installer will remove Arc as a composer dependency.

Please Note: If you choose to use the CI/CD configurations then there are some local environment variables that are required before you can run the containers

    export DOCKER_USERNAME=myUsername
    export DOCKER_REPO=my-repo
    export TAG=latest

    export GITHUB_TOKEN=1234567890 # optional
```

But after running `php artisan arc:install` I was not prompted to configure CI/CD

I then did realize that the CI/CD was added after the Release 2.1, so I undid everything this time installed with `composer require richdynamix/arc:dev-maste`

And this time it did prompt me, which installed a lot of extra files also referenced in the current Readme. Anyway just pointing out that this could be confusing to others trying out your very useful package

Keep up the great work and thanks for making this!

**Comment by richdynamix** [comment]
This was due to the `master` branch being worked on separately from a stable release. I have released a new version which should bring all these items together.
