### ISSUE TITLE
PHP 7.3, Ubuntu 18.04 and MySQL 8

### ISSUE THREAD

**Issue by vesper8** [richdynamix/arc#17]
I notice that in the Readme it mentions PHP 7.2, a parent Nginx image based on Ubuntu 16.04 and MySQL 5.7

Just wondering if it's possible to use your dockerfiles but with the most recent dependencies as listed in this issue's title?

Thanks a lot

**Comment by plexcellmedia** [comment]
For local development you can replace MySQL version to anything you want, there shouldn't be any problems using your choise of MySQL.

For production, we used Google Cloud SQL. Just to get access to usefull features such as backups and user management easily. Also there wasnt kubernetes files for MySQL setup, so you have to make them by yourself if you want to run MySQL on kubernetes engine.

**Comment by richdynamix** [comment]
Unfortunately the parent image has not been updated yet to include PHP 7.3. When this has been done I will update the README accordingly. As @plexcellmedia suggests, you are free to use which ever version of MySQL image for the DB for local development.
