### ISSUE TITLE
Scalability question

### ISSUE THREAD

**Issue by RamonSmit** [richdynamix/arc#2]
Hi There, 

Thanks for creating this awesome docker image! It really helps me out with my website.

I have a small question about the image. I'm running it in Rancher and want to scale to more then 
one instance, but the idea of multiple horizon instances and crons creeps me out. 

Is there a way to enable horizon/cron to one instance?

With kind regards, 
Ramon

**Comment by richdynamix** [comment]
Sure, you would have one master pod that can set the environment variables for CRON and Horizon while your replica pods would not. This can be done via your Kubernetes configuration.

From here -https://github.com/richdynamix/arc/blob/master/tools/docker/usr/local/share/env/20-arc-env#L3-L10 you can determine which are on and off per environment.

**Comment by RamonSmit** [comment]
That sounds like a brilliant idea. Just one worker pod for handing CRON and Horizon and just some Web pod-workers!

I'm going to try this out! Thanks for the feedback!

**Comment by richdynamix** [comment]
No worries, your welcome.

**Comment by RamonSmit** [comment]
Fought with this, got it working now! Thanks!
