### ISSUE TITLE
Support laravel 8

### ISSUE THREAD

**Issue by 96rajabi** [richdynamix/arc#23]
Problem 1
    - Root composer.json requires richdynamix/arc ^3.0 -> satisfiable by richdynamix/arc[3.0.0].
    - richdynamix/arc 3.0.0 requires illuminate/support ~6.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev] but it conflicts with another require.

**Comment by richdynamix** [comment]
Hi, Arc has now been updated to resolve this issue - https://github.com/richdynamix/arc/releases/tag/4.0.0
