### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Nerd2201** [richdynamix/arc#7]
Can you please add a cert-bot for providing https and tls certs by default? that will be really nice

**Comment by richdynamix** [comment]
HTTPS is available by default and is applied using the ENV here. https://github.com/richdynamix/arc/blob/master/tools/docker/usr/local/share/env/20-arc-env#L10 

For more information on how this is created see the parent image - 
https://github.com/continuouspipe/dockerfiles/tree/master/php/nginx
